name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-mac:
    name: Build for Mac
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: benji4000.mac
        path: |
          benji4000
          src/
        
        

  build-win:
    name: Build for Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: benji4000.win
        path: |
          benji4000.EXE
          src/
